/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class diordve_bonebou_preNocr */

#ifndef _Included_diordve_bonebou_preNocr
#define _Included_diordve_bonebou_preNocr
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     diordve_bonebou_preNocr
 * Method:    doit
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_diordve_bonebou_preNocr_doit
(JNIEnv *, jobject, jstring, jstring);


#ifdef __cplusplus
}
#endif
#endif
